### ISSUE TITLE
fail to import py3d

### ISSUE THREAD

**Issue by yux11** [ericmjonas/pybm3d#10]
When I try to import pybm3d, it raises this error:

ImportError: dlopen(/.../anaconda3/lib/python3.6/site-packages/pybm3d/bm3d.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/opt/libtiff/lib/libtiff.5.dylib
  Referenced from: /.../anaconda3/lib/python3.6/site-packages/pybm3d/bm3d.cpython-36m-darwin.so
  Reason: image not found

Can someone help me out?

**Comment by timmeinhardt** [comment]
Hello,

if you install `brew install libtiff` prior to the anaconda installation of PyBM3D it should work. But I will check why this is actually needed. The only dependency should be FFTW3.

Do not hesitate to ask if you have further problems.

**Comment by yux11** [comment]
It works now. Thank you so much!
