### ISSUE TITLE
import pybm3d into namespace 

### ISSUE THREAD

**Issue by ericmjonas** [ericmjonas/pybm3d#2]

**Comment by timmeinhardt** [comment]
@ericmjonas What was your intention behind this issue?

**Comment by ericmjonas** [comment]
I think at the time the cython wrapper had to be manually imported in an awkward fashion, and the thought was to get it into the top-level module namespace for easier use?

**Comment by timmeinhardt** [comment]
The lates commit of the develop branch https://github.com/ericmjonas/pybm3d/commit/9a49a2491ed4058cf35fae3e79b6718c5a058193 changes the interface and imports the `bm3d` function directly into the package's namespace. Is this what you had in mind?

**Comment by ericmjonas** [comment]
Yes that’s awesome !
